### ISSUE TITLE
Check wysiwyg option

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-plugin-comments#5]
When wysiwyg option is enabled for comments, they are not saved and this message is shown:  
![image](https://user-images.githubusercontent.com/7892851/29483880-e0585418-84d3-11e7-9318-b333b39769e3.png)

**Comment by CKENT0369** [comment]
I have this problem too added a bug under subrion

**Comment by ghost** [comment]
Fixed: https://github.com/intelliants/subrion-plugin-comments/commit/edda80a12b25aa94ed152419146a71878375c17b

**Comment by CKENT0369** [comment]
Great this portion is fixed. Thank you.

**Comment by CKENT0369** [comment]
Great this portion is fixed. Thank you.

**Comment by vbezruchkin** [comment]
Thanks for the confirmation.
