### ISSUE TITLE
Update for 4.2

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-plugin-comments#9]

**Comment by Chehadeej** [comment]
do we have a tentative date to close this issue?

**Comment by 4unkur** [comment]
The plugin has been updated and released https://subrion.org/plugin/comments.html

You can download it via admin panel too.

If you already have this plugins old version installed, then uninstall it in admin panel, remove plugin's folder in /modules
Then install new version in admin panel, but before that you might need to clear the cache.

Thanks.
